import { BadgeCheck, BriefcaseBusiness, Building2, Globe2, Mail, Phone, Save, User } from "lucide-react";
import { useEffect, useState } from "react";
import ErrorBanner from "../components/ErrorBanner";
import LoadingSpinner from "../components/LoadingSpinner";
import PageHeader from "../components/PageHeader";
import { useAuth } from "../context/AuthContext";
import { Field } from "./Login";

export default function Profile() {
  const { user, updateProfile } = useAuth();
  const [form, setForm] = useState({ name: "", phone: "", organization: "", job_title: "", jurisdiction: "", professional_id: "" });
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { if (user) setForm({ name: user.name || "", phone: user.phone || "", organization: user.organization || "", job_title: user.job_title || "", jurisdiction: user.jurisdiction || "", professional_id: user.professional_id || "" }); }, [user]);
  const update = (field) => (event) => setForm({ ...form, [field]: event.target.value });
  async function handleSubmit(event) { event.preventDefault(); setError(""); setMessage(""); setLoading(true); try { const response = await updateProfile(form); setMessage(response.message); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  return <><PageHeader eyebrow="Account" title="Professional profile" description="Keep your identity and professional details current." /><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_18rem]"><form onSubmit={handleSubmit} className="panel rounded-2xl p-5 sm:p-7"><ErrorBanner message={error} />{message ? <div className="mb-5 rounded-xl border border-teal-200 bg-teal-50 p-4 text-sm font-semibold text-teal-800 dark:border-teal-400/20 dark:bg-teal-400/10 dark:text-teal-200">{message}</div> : null}<div className="grid gap-5 sm:grid-cols-2"><Field label="Full name" icon={User}><input className="input pl-11" autoComplete="name" value={form.name} onChange={update("name")} required /></Field><Field label="Email address" icon={Mail}><input className="input pl-11 disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-600 dark:disabled:bg-white/[0.03] dark:disabled:text-slate-400" value={user?.email || ""} disabled /></Field><Field label="Phone number" icon={Phone}><input className="input pl-11" autoComplete="tel" value={form.phone} onChange={update("phone")} /></Field><Field label="Organization / firm" icon={Building2}><input className="input pl-11" autoComplete="organization" value={form.organization} onChange={update("organization")} /></Field><Field label="Job title" icon={BriefcaseBusiness}><input className="input pl-11" value={form.job_title} onChange={update("job_title")} /></Field><Field label="Jurisdiction" icon={Globe2}><input className="input pl-11" value={form.jurisdiction} onChange={update("jurisdiction")} /></Field><Field label="Bar / professional ID" icon={BadgeCheck}><input className="input pl-11" value={form.professional_id} onChange={update("professional_id")} /></Field></div><button className="btn-primary mt-6" disabled={loading}>{loading ? <LoadingSpinner label="Saving profile" /> : <><Save className="h-4 w-4" /> Save changes</>}</button></form><aside className="panel h-fit rounded-2xl p-6 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-2xl bg-gradient-to-br from-teal-400 to-cyan-500 text-2xl font-extrabold text-vault-950">{(user?.name || "U").charAt(0).toUpperCase()}</div><p className="mt-4 font-bold text-slate-950 dark:text-white">{user?.name}</p><p className="mt-1 break-all text-sm text-slate-600 dark:text-slate-300">{user?.email}</p><span className="mt-4 inline-flex rounded-full bg-teal-50 px-3 py-1 text-xs font-bold capitalize text-teal-800 dark:bg-teal-400/10 dark:text-teal-200">{user?.role || "user"}</span></aside></div></>;
}
